name: flutter_base_bloc
description: Flutter base with Bloc

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  auto_route: 7.8.0
  bloc: ^8.1.4
  dio: ^5.4.3+1
  flutter_screenutil: ^5.9.0
  auto_size_text: ^3.0.0
  velocity_x: 3.6.0
  flutter_svg: 2.0.2
  cached_network_image: ^3.2.3
  intl: ^0.17.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  freerasp: ^6.5.1
  package_info_plus: ^4.2.0
  retrofit: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  auto_route_generator: 7.3.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/locales/
    - assets/images/
    - assets/fonts/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
